import { test } from '@playwright/test';

test('omre recorded flow', async ({ page }) => {
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('H@ppy7878');
    await page.getByRole('button', { name: 'Show password' }).click();
    await page.getByRole('button', { name: 'Log In' }).click();
    await page.locator('#radix-_r_3u_').click();
    await page.locator('html').click();
    await page.goto('https://omre.ai/app/explore');
    await page.getByRole('tab', { name: 'Reels' }).click();
    await page.getByRole('button', { name: 'Later' }).click();
    await page.getByRole('link', { name: 'Shorts Shorts' }).click();
    await page.locator('button').filter({ hasText: '4944' }).click();
    await page.locator('button').filter({ hasText: '4944' }).click();
    await page.getByRole('link', { name: 'Subscriptions Subscriptions' }).click();
    await page.getByRole('link', { name: 'My Channel My Channel' }).click();
    await page.getByRole('link', { name: 'Social Post Share with your' }).click();
    await page.getByRole('button', { name: 'News News' }).click();
    await page.goto('https://omre.ai/app/news/home');
    await page.getByRole('button', { name: 'Mart Mart' }).click();
    await page.getByRole('button', { name: 'Games Games' }).click();
    await page.getByRole('button', { name: 'Meetings Meetings' }).click();
    await page.locator('.h-12').first().click();
    await page.locator('html').click();
    await page.getByRole('button', { name: 'Wallet Wallet' }).click();
    await page.getByRole('button', { name: 'Account menu' }).click();
    await page.getByLabel('', { exact: true }).getByText('Settings').click();
    await page.getByRole('link', { name: 'AI Studio AI features,' }).click();
    await page.getByRole('button', { name: 'Social Social' }).click();
    await page.getByRole('link', { name: 'Pages Pages' }).click();
    await page.getByRole('button', { name: 'Create page' }).click();
    await page.getByRole('button', { name: 'Close' }).click();
    await page.getByRole('button', { name: 'Create page' }).click();
    await page.getByRole('button', { name: 'Close' }).click();
    await page.getByRole('link', { name: 'Groups Groups' }).click();
    await page.getByRole('link', { name: 'Discover' }).click();
    await page.getByRole('button', { name: 'Join Community' }).first().click();
    await page.getByRole('button', { name: 'Social Social' }).click();
    await page.getByRole('link', { name: 'Weather Weather' }).click();
    await page.goto('https://omre.ai/app/images');
    await page.getByRole('link', { name: 'Friends Friends' }).click();
    await page.goto('https://omre.ai/app/friends');
    await page.getByRole('button', { name: 'Messages' }).click();
    await page.getByRole('button', { name: 'System Toggle theme' }).click();
});
